# Generated by Django 4.1.4 on 2023-01-27 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_categoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='imagen',
        ),
    ]
