# Generated by Django 4.1.4 on 2023-01-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_categoria_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='activo',
        ),
    ]
